name: cargo-publish

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  publish:

    runs-on: ubuntu-latest

    environment:
      name: crates.io

    steps:
      - uses: actions/checkout@v4

      - name: Publish crate
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

