name: cargo-deny

on:
  schedule:
    - cron: "48 22 * * 3"
  push:
  pull_request:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
